import Barcode from "react-barcode"
import type { Order, OrderItem } from "@/lib/types"

type ShippingLabelProps = {
  order: Order
  items: OrderItem[]
}

export function ShippingLabel({ order, items }: ShippingLabelProps) {
  const awb = order.awb_nr ?? "—"
  const orderNr = order.fbpi_order_nr ?? "—"
  const warehouse = order.warehouse_code ?? "—"
  const date = order.order_created_at
    ? new Date(order.order_created_at).toLocaleDateString()
    : "—"

  return (
    <div className="shipping-label mx-auto w-[400px] bg-white p-6 text-black print:shadow-none print:border-0">
      <div className="mb-4 border-b-2 border-black pb-2">
        <h1 className="text-lg font-bold tracking-tight">Shipping Label</h1>
        <p className="text-xs text-gray-600">Generated by NexCommerce</p>
      </div>

      <div className="mb-4 grid grid-cols-2 gap-x-4 gap-y-2 text-sm">
        <div>
          <p className="text-[10px] font-semibold uppercase text-gray-500">Order Number</p>
          <p className="font-mono font-medium">{orderNr}</p>
        </div>
        <div>
          <p className="text-[10px] font-semibold uppercase text-gray-500">Warehouse</p>
          <p className="font-mono">{warehouse}</p>
        </div>
        <div>
          <p className="text-[10px] font-semibold uppercase text-gray-500">Date</p>
          <p>{date}</p>
        </div>
        <div>
          <p className="text-[10px] font-semibold uppercase text-gray-500">Country</p>
          <p>{order.customer_country_code ?? "—"}</p>
        </div>
      </div>

      <div className="mb-4">
        <p className="text-[10px] font-semibold uppercase text-gray-500">AWB Number</p>
        <p className="font-mono text-base font-bold">{awb}</p>
      </div>

      <div className="mb-4 flex justify-center border-y border-dashed border-gray-300 py-4">
        {order.awb_nr ? (
          <Barcode
            value={order.awb_nr}
            format="CODE128"
            width={2}
            height={60}
            displayValue
            fontSize={14}
            margin={0}
          />
        ) : (
          <p className="text-sm text-gray-400">No AWB number available</p>
        )}
      </div>

      <div>
        <p className="mb-1 text-[10px] font-semibold uppercase text-gray-500">
          Line Items ({items.length})
        </p>
        <table className="w-full text-xs">
          <thead>
            <tr className="border-b border-gray-300 text-left">
              <th className="py-1 pr-2 font-semibold">Item #</th>
              <th className="py-1 pr-2 font-semibold">SKU</th>
              <th className="py-1 text-right font-semibold">Price</th>
            </tr>
          </thead>
          <tbody>
            {items.map((item) => (
              <tr key={item.mp_item_nr} className="border-b border-gray-100">
                <td className="py-1 pr-2 font-mono">{item.mp_item_nr}</td>
                <td className="py-1 pr-2 font-mono">{item.partner_sku ?? "—"}</td>
                <td className="py-1 text-right tabular-nums">
                  {item.price != null ? Number(item.price).toFixed(2) : "—"}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  )
}
